[package]
name = "cmd-wrapper"
version = "1.0.0"
edition = "2024"

authors = ["RenovZ <cgsixv@gmail.com>"]
description = "A command wrapped for easy use cases"
license = "MIT"
repository = "https://github.com/RenovZ/cmd-wrapper"
readme = "README.md"
keywords = ["command", "command-wrapper", "async", "tokio"]

[dependencies]
tokio = { version = "1.46", features = ["full"] }
tracing = "0.1"
derivative = "2.2"
